# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any

import ctypes
import struct

class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_meshllm_ffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_meshllm_ffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_meshllm_ffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiFfiConverterByRefBytes:
    """Zero-copy converter for `&[u8]` / `[ByRef] bytes` arguments.

    Only `lower` and `check_lower` are valid — zero-copy byte buffers only
    flow foreign -> Rust, and only in argument position. `lift`, `read`, and
    `write` have no sound implementation here.

    CPython `bytes` objects are immutable and their internal buffer doesn't
    move for the lifetime of the object; the caller must keep the source
    `bytes` alive for the duration of the FFI call.
    """

    @staticmethod
    def check_lower(value):
        # Tighter than `bytes-like`: `lower` uses `ctypes.c_char_p` which only
        # accepts `bytes`/`None`, so fail fast with a matching check.
        if not isinstance(value, bytes):
            raise TypeError("a bytes object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def lower(value):
        fb = _UniffiForeignBytes()
        if len(value) == 0:
            fb.len = 0
            fb.data = None
        else:
            fb.len = len(value)
            fb.data = ctypes.cast(ctypes.c_char_p(value), ctypes.POINTER(ctypes.c_char))
        return fb

    @staticmethod
    def lift(value):
        raise NotImplementedError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    @staticmethod
    def read(buf):
        raise NotImplementedError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    @staticmethod
    def write(value, buf):
        raise NotImplementedError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            packed = struct.pack(format, value)
            if size > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, packed, size)

    def write(self, value):
        length = len(value)
        with self._reserve(length):
            if length > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, value, length)

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles.
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()# Magic number for the Rust proxy to call using the same mechanism as every other method,
# to free the callback once it's dropped by Rust.
_UNIFFI_IDX_CALLBACK_FREE = 0
# Return codes for callback calls
_UNIFFI_CALLBACK_SUCCESS = 0
_UNIFFI_CALLBACK_ERROR = 1
_UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

class _UniffiCallbackInterfaceFfiConverter:
    _handle_map = _UniffiHandleMap()

    @classmethod
    def lift(cls, handle):
        return cls._handle_map.get(handle)

    @classmethod
    def read(cls, buf):
        handle = buf.read_u64()
        cls.lift(handle)

    @classmethod
    def check_lower(cls, cb):
        pass

    @classmethod
    def lower(cls, cb):
        handle = cls._handle_map.insert(cb)
        return handle

    @classmethod
    def write(cls, cb, buf):
        buf.write_u64(cls.lower(cb))

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("uniffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_meshllm_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_meshllm_ffi_checksum_func_create_node() != 63700:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_func_current_mesh_version() != 41756:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_func_current_skippy_abi_version() != 53670:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_func_install_native_runtime() != 48746:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_func_installed_native_runtimes() != 16961:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_func_prune_native_runtimes() != 11380:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_func_remove_native_runtime() != 54339:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_cancel() != 47545:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_inference_list_models() != 41613:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_join_token() != 57356:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_openai_request() != 19585:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_openai_stream() != 40368:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_start() != 46124:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_status() != 42366:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_stop() != 10537:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_meshllm_ffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_meshllm_ffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_meshllm_ffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_meshllm_ffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_meshllm_ffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_meshllm_ffi_rustbuffer_free.restype = None
_UniffiLib.ffi_meshllm_ffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_meshllm_ffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_meshllm_ffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_meshllm_ffi_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_meshllm_ffi_checksum_func_create_node.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_create_node.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_func_current_mesh_version.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_current_mesh_version.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_func_current_skippy_abi_version.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_current_skippy_abi_version.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_func_install_native_runtime.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_install_native_runtime.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_func_installed_native_runtimes.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_installed_native_runtimes.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_func_prune_native_runtimes.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_prune_native_runtimes.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_func_remove_native_runtime.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_func_remove_native_runtime.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_cancel.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_cancel.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_inference_list_models.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_inference_list_models.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_join_token.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_join_token.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_openai_request.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_openai_request.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_openai_stream.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_openai_stream.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_start.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_start.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_status.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_status.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_stop.argtypes = (
)
_UniffiLib.uniffi_meshllm_ffi_checksum_method_meshnodehandle_stop.restype = ctypes.c_uint16
_UniffiLib.uniffi_meshllm_ffi_fn_func_create_node.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_int8,
    _UniffiRustBuffer,
    ctypes.c_uint16,
    ctypes.c_uint16,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_create_node.restype = ctypes.c_uint64
_UniffiLib.uniffi_meshllm_ffi_fn_func_current_mesh_version.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_current_mesh_version.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_func_current_skippy_abi_version.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_current_skippy_abi_version.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_func_install_native_runtime.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_install_native_runtime.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_func_installed_native_runtimes.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_installed_native_runtimes.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_func_prune_native_runtimes.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_prune_native_runtimes.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_func_remove_native_runtime.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_func_remove_native_runtime.restype = ctypes.c_int8
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_cancel.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_cancel.restype = None
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_inference_list_models.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_inference_list_models.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_join_token.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_join_token.restype = None
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_openai_request.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_openai_request.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_openai_stream.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_openai_stream.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_start.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_start.restype = None
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_status.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_status.restype = _UniffiRustBuffer
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_stop.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_stop.restype = None
_UniffiLib.uniffi_meshllm_ffi_fn_clone_meshnodehandle.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_clone_meshnodehandle.restype = ctypes.c_uint64
_UniffiLib.uniffi_meshllm_ffi_fn_free_meshnodehandle.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_meshllm_ffi_fn_free_meshnodehandle.restype = None
_UNIFFI_CALLBACK_INTERFACE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_CLONE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER = ctypes.CFUNCTYPE(ctypes.c_uint64,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiVTableCallbackInterfaceMeshFfiNativeRuntimeProgressListener(ctypes.Structure):
    _fields_ = [
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER),
        ("uniffi_clone", _UNIFFI_CALLBACK_INTERFACE_CLONE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER),
        ("on_progress", _UNIFFI_CALLBACK_INTERFACE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER_METHOD0),
    ]
_UniffiLib.uniffi_meshllm_ffi_fn_init_callback_vtable_nativeruntimeprogresslistener.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceMeshFfiNativeRuntimeProgressListener),
)
_UniffiLib.uniffi_meshllm_ffi_fn_init_callback_vtable_nativeruntimeprogresslistener.restype = None
_UNIFFI_CALLBACK_INTERFACE_MESH_FFI_OPEN_AI_STREAM_LISTENER_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_CLONE_MESH_FFI_OPEN_AI_STREAM_LISTENER = ctypes.CFUNCTYPE(ctypes.c_uint64,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE_MESH_FFI_OPEN_AI_STREAM_LISTENER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiVTableCallbackInterfaceMeshFfiOpenAiStreamListener(ctypes.Structure):
    _fields_ = [
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE_MESH_FFI_OPEN_AI_STREAM_LISTENER),
        ("uniffi_clone", _UNIFFI_CALLBACK_INTERFACE_CLONE_MESH_FFI_OPEN_AI_STREAM_LISTENER),
        ("on_event", _UNIFFI_CALLBACK_INTERFACE_MESH_FFI_OPEN_AI_STREAM_LISTENER_METHOD0),
    ]
_UniffiLib.uniffi_meshllm_ffi_fn_init_callback_vtable_openaistreamlistener.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceMeshFfiOpenAiStreamListener),
)
_UniffiLib.uniffi_meshllm_ffi_fn_init_callback_vtable_openaistreamlistener.restype = None

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class InstalledNativeRuntimeNative:
    def __init__(self, *, mesh_version:str, native_runtime_id:str, flavor:str, path:str, skippy_abi_version:typing.Optional[str]):
        self.mesh_version = mesh_version
        self.native_runtime_id = native_runtime_id
        self.flavor = flavor
        self.path = path
        self.skippy_abi_version = skippy_abi_version




    def __str__(self):
        return "InstalledNativeRuntimeNative(mesh_version={}, native_runtime_id={}, flavor={}, path={}, skippy_abi_version={})".format(self.mesh_version, self.native_runtime_id, self.flavor, self.path, self.skippy_abi_version)
    def __eq__(self, other):
        if self.mesh_version != other.mesh_version:
            return False
        if self.native_runtime_id != other.native_runtime_id:
            return False
        if self.flavor != other.flavor:
            return False
        if self.path != other.path:
            return False
        if self.skippy_abi_version != other.skippy_abi_version:
            return False
        return True

class _UniffiFfiConverterTypeInstalledNativeRuntimeNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return InstalledNativeRuntimeNative(
            mesh_version=_UniffiFfiConverterString.read(buf),
            native_runtime_id=_UniffiFfiConverterString.read(buf),
            flavor=_UniffiFfiConverterString.read(buf),
            path=_UniffiFfiConverterString.read(buf),
            skippy_abi_version=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.mesh_version)
        _UniffiFfiConverterString.check_lower(value.native_runtime_id)
        _UniffiFfiConverterString.check_lower(value.flavor)
        _UniffiFfiConverterString.check_lower(value.path)
        _UniffiFfiConverterOptionalString.check_lower(value.skippy_abi_version)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.mesh_version, buf)
        _UniffiFfiConverterString.write(value.native_runtime_id, buf)
        _UniffiFfiConverterString.write(value.flavor, buf)
        _UniffiFfiConverterString.write(value.path, buf)
        _UniffiFfiConverterOptionalString.write(value.skippy_abi_version, buf)

class _UniffiFfiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)

class _UniffiFfiConverterOptionalUInt32(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt32.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt32.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt32.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class ModelNative:
    def __init__(self, *, id:str, name:str, context_length:typing.Optional[int]):
        self.id = id
        self.name = name
        self.context_length = context_length




    def __str__(self):
        return "ModelNative(id={}, name={}, context_length={})".format(self.id, self.name, self.context_length)
    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self.name != other.name:
            return False
        if self.context_length != other.context_length:
            return False
        return True

class _UniffiFfiConverterTypeModelNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ModelNative(
            id=_UniffiFfiConverterString.read(buf),
            name=_UniffiFfiConverterString.read(buf),
            context_length=_UniffiFfiConverterOptionalUInt32.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.id)
        _UniffiFfiConverterString.check_lower(value.name)
        _UniffiFfiConverterOptionalUInt32.check_lower(value.context_length)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.id, buf)
        _UniffiFfiConverterString.write(value.name, buf)
        _UniffiFfiConverterOptionalUInt32.write(value.context_length, buf)

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterOptionalUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt64.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

@dataclass
class NativeRuntimeDownloadProgressNative:
    def __init__(self, *, native_runtime_id:str, url:str, downloaded_bytes:int, total_bytes:typing.Optional[int], finished:bool):
        self.native_runtime_id = native_runtime_id
        self.url = url
        self.downloaded_bytes = downloaded_bytes
        self.total_bytes = total_bytes
        self.finished = finished




    def __str__(self):
        return "NativeRuntimeDownloadProgressNative(native_runtime_id={}, url={}, downloaded_bytes={}, total_bytes={}, finished={})".format(self.native_runtime_id, self.url, self.downloaded_bytes, self.total_bytes, self.finished)
    def __eq__(self, other):
        if self.native_runtime_id != other.native_runtime_id:
            return False
        if self.url != other.url:
            return False
        if self.downloaded_bytes != other.downloaded_bytes:
            return False
        if self.total_bytes != other.total_bytes:
            return False
        if self.finished != other.finished:
            return False
        return True

class _UniffiFfiConverterTypeNativeRuntimeDownloadProgressNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return NativeRuntimeDownloadProgressNative(
            native_runtime_id=_UniffiFfiConverterString.read(buf),
            url=_UniffiFfiConverterString.read(buf),
            downloaded_bytes=_UniffiFfiConverterUInt64.read(buf),
            total_bytes=_UniffiFfiConverterOptionalUInt64.read(buf),
            finished=_UniffiFfiConverterBoolean.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.native_runtime_id)
        _UniffiFfiConverterString.check_lower(value.url)
        _UniffiFfiConverterUInt64.check_lower(value.downloaded_bytes)
        _UniffiFfiConverterOptionalUInt64.check_lower(value.total_bytes)
        _UniffiFfiConverterBoolean.check_lower(value.finished)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.native_runtime_id, buf)
        _UniffiFfiConverterString.write(value.url, buf)
        _UniffiFfiConverterUInt64.write(value.downloaded_bytes, buf)
        _UniffiFfiConverterOptionalUInt64.write(value.total_bytes, buf)
        _UniffiFfiConverterBoolean.write(value.finished, buf)

class _UniffiFfiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterString.read(buf) for i in range(count)
        ]






class NativeRuntimeVerificationPolicyNative(enum.Enum):

    REQUIRE_CHECKSUM = 0

    REQUIRE_CHECKSUM_AND_SIGNATURE = 1



class _UniffiFfiConverterTypeNativeRuntimeVerificationPolicyNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return NativeRuntimeVerificationPolicyNative.REQUIRE_CHECKSUM
        if variant == 2:
            return NativeRuntimeVerificationPolicyNative.REQUIRE_CHECKSUM_AND_SIGNATURE
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == NativeRuntimeVerificationPolicyNative.REQUIRE_CHECKSUM:
            return
        if value == NativeRuntimeVerificationPolicyNative.REQUIRE_CHECKSUM_AND_SIGNATURE:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == NativeRuntimeVerificationPolicyNative.REQUIRE_CHECKSUM:
            buf.write_i32(1)
        if value == NativeRuntimeVerificationPolicyNative.REQUIRE_CHECKSUM_AND_SIGNATURE:
            buf.write_i32(2)



@dataclass
class NativeRuntimeInstallOptionsNative:
    def __init__(self, *, mesh_version:typing.Optional[str], skippy_abi_version:typing.Optional[str], selection:str, manifest_path:typing.Optional[str], manifest_url:typing.Optional[str], bundle_dirs:typing.List[str], cache_dir:typing.Optional[str], verification_policy:NativeRuntimeVerificationPolicyNative, allow_download:bool):
        self.mesh_version = mesh_version
        self.skippy_abi_version = skippy_abi_version
        self.selection = selection
        self.manifest_path = manifest_path
        self.manifest_url = manifest_url
        self.bundle_dirs = bundle_dirs
        self.cache_dir = cache_dir
        self.verification_policy = verification_policy
        self.allow_download = allow_download




    def __str__(self):
        return "NativeRuntimeInstallOptionsNative(mesh_version={}, skippy_abi_version={}, selection={}, manifest_path={}, manifest_url={}, bundle_dirs={}, cache_dir={}, verification_policy={}, allow_download={})".format(self.mesh_version, self.skippy_abi_version, self.selection, self.manifest_path, self.manifest_url, self.bundle_dirs, self.cache_dir, self.verification_policy, self.allow_download)
    def __eq__(self, other):
        if self.mesh_version != other.mesh_version:
            return False
        if self.skippy_abi_version != other.skippy_abi_version:
            return False
        if self.selection != other.selection:
            return False
        if self.manifest_path != other.manifest_path:
            return False
        if self.manifest_url != other.manifest_url:
            return False
        if self.bundle_dirs != other.bundle_dirs:
            return False
        if self.cache_dir != other.cache_dir:
            return False
        if self.verification_policy != other.verification_policy:
            return False
        if self.allow_download != other.allow_download:
            return False
        return True

class _UniffiFfiConverterTypeNativeRuntimeInstallOptionsNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return NativeRuntimeInstallOptionsNative(
            mesh_version=_UniffiFfiConverterOptionalString.read(buf),
            skippy_abi_version=_UniffiFfiConverterOptionalString.read(buf),
            selection=_UniffiFfiConverterString.read(buf),
            manifest_path=_UniffiFfiConverterOptionalString.read(buf),
            manifest_url=_UniffiFfiConverterOptionalString.read(buf),
            bundle_dirs=_UniffiFfiConverterSequenceString.read(buf),
            cache_dir=_UniffiFfiConverterOptionalString.read(buf),
            verification_policy=_UniffiFfiConverterTypeNativeRuntimeVerificationPolicyNative.read(buf),
            allow_download=_UniffiFfiConverterBoolean.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterOptionalString.check_lower(value.mesh_version)
        _UniffiFfiConverterOptionalString.check_lower(value.skippy_abi_version)
        _UniffiFfiConverterString.check_lower(value.selection)
        _UniffiFfiConverterOptionalString.check_lower(value.manifest_path)
        _UniffiFfiConverterOptionalString.check_lower(value.manifest_url)
        _UniffiFfiConverterSequenceString.check_lower(value.bundle_dirs)
        _UniffiFfiConverterOptionalString.check_lower(value.cache_dir)
        _UniffiFfiConverterTypeNativeRuntimeVerificationPolicyNative.check_lower(value.verification_policy)
        _UniffiFfiConverterBoolean.check_lower(value.allow_download)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterOptionalString.write(value.mesh_version, buf)
        _UniffiFfiConverterOptionalString.write(value.skippy_abi_version, buf)
        _UniffiFfiConverterString.write(value.selection, buf)
        _UniffiFfiConverterOptionalString.write(value.manifest_path, buf)
        _UniffiFfiConverterOptionalString.write(value.manifest_url, buf)
        _UniffiFfiConverterSequenceString.write(value.bundle_dirs, buf)
        _UniffiFfiConverterOptionalString.write(value.cache_dir, buf)
        _UniffiFfiConverterTypeNativeRuntimeVerificationPolicyNative.write(value.verification_policy, buf)
        _UniffiFfiConverterBoolean.write(value.allow_download, buf)

@dataclass
class NativeRuntimeInstallOutcomeNative:
    def __init__(self, *, status:str, runtime:InstalledNativeRuntimeNative, selected_native_runtime_id:str, selected_source:str):
        self.status = status
        self.runtime = runtime
        self.selected_native_runtime_id = selected_native_runtime_id
        self.selected_source = selected_source




    def __str__(self):
        return "NativeRuntimeInstallOutcomeNative(status={}, runtime={}, selected_native_runtime_id={}, selected_source={})".format(self.status, self.runtime, self.selected_native_runtime_id, self.selected_source)
    def __eq__(self, other):
        if self.status != other.status:
            return False
        if self.runtime != other.runtime:
            return False
        if self.selected_native_runtime_id != other.selected_native_runtime_id:
            return False
        if self.selected_source != other.selected_source:
            return False
        return True

class _UniffiFfiConverterTypeNativeRuntimeInstallOutcomeNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return NativeRuntimeInstallOutcomeNative(
            status=_UniffiFfiConverterString.read(buf),
            runtime=_UniffiFfiConverterTypeInstalledNativeRuntimeNative.read(buf),
            selected_native_runtime_id=_UniffiFfiConverterString.read(buf),
            selected_source=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.status)
        _UniffiFfiConverterTypeInstalledNativeRuntimeNative.check_lower(value.runtime)
        _UniffiFfiConverterString.check_lower(value.selected_native_runtime_id)
        _UniffiFfiConverterString.check_lower(value.selected_source)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.status, buf)
        _UniffiFfiConverterTypeInstalledNativeRuntimeNative.write(value.runtime, buf)
        _UniffiFfiConverterString.write(value.selected_native_runtime_id, buf)
        _UniffiFfiConverterString.write(value.selected_source, buf)

@dataclass
class NativeRuntimePruneResultNative:
    def __init__(self, *, removed_dirs:typing.List[str]):
        self.removed_dirs = removed_dirs




    def __str__(self):
        return "NativeRuntimePruneResultNative(removed_dirs={})".format(self.removed_dirs)
    def __eq__(self, other):
        if self.removed_dirs != other.removed_dirs:
            return False
        return True

class _UniffiFfiConverterTypeNativeRuntimePruneResultNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return NativeRuntimePruneResultNative(
            removed_dirs=_UniffiFfiConverterSequenceString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceString.check_lower(value.removed_dirs)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceString.write(value.removed_dirs, buf)

@dataclass
class NodeStatusNative:
    def __init__(self, *, running:bool, mode:str, api_base_url:str, console_url:str, payload_json:str):
        self.running = running
        self.mode = mode
        self.api_base_url = api_base_url
        self.console_url = console_url
        self.payload_json = payload_json




    def __str__(self):
        return "NodeStatusNative(running={}, mode={}, api_base_url={}, console_url={}, payload_json={})".format(self.running, self.mode, self.api_base_url, self.console_url, self.payload_json)
    def __eq__(self, other):
        if self.running != other.running:
            return False
        if self.mode != other.mode:
            return False
        if self.api_base_url != other.api_base_url:
            return False
        if self.console_url != other.console_url:
            return False
        if self.payload_json != other.payload_json:
            return False
        return True

class _UniffiFfiConverterTypeNodeStatusNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return NodeStatusNative(
            running=_UniffiFfiConverterBoolean.read(buf),
            mode=_UniffiFfiConverterString.read(buf),
            api_base_url=_UniffiFfiConverterString.read(buf),
            console_url=_UniffiFfiConverterString.read(buf),
            payload_json=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterBoolean.check_lower(value.running)
        _UniffiFfiConverterString.check_lower(value.mode)
        _UniffiFfiConverterString.check_lower(value.api_base_url)
        _UniffiFfiConverterString.check_lower(value.console_url)
        _UniffiFfiConverterString.check_lower(value.payload_json)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterBoolean.write(value.running, buf)
        _UniffiFfiConverterString.write(value.mode, buf)
        _UniffiFfiConverterString.write(value.api_base_url, buf)
        _UniffiFfiConverterString.write(value.console_url, buf)
        _UniffiFfiConverterString.write(value.payload_json, buf)

class _UniffiFfiConverterUInt16(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u16"
    VALUE_MIN = 0
    VALUE_MAX = 2**16

    @staticmethod
    def read(buf):
        return buf.read_u16()

    @staticmethod
    def write(value, buf):
        buf.write_u16(value)

@dataclass
class OpenAiResponseNative:
    def __init__(self, *, status_code:int, content_type:typing.Optional[str], body:str):
        self.status_code = status_code
        self.content_type = content_type
        self.body = body




    def __str__(self):
        return "OpenAiResponseNative(status_code={}, content_type={}, body={})".format(self.status_code, self.content_type, self.body)
    def __eq__(self, other):
        if self.status_code != other.status_code:
            return False
        if self.content_type != other.content_type:
            return False
        if self.body != other.body:
            return False
        return True

class _UniffiFfiConverterTypeOpenAiResponseNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return OpenAiResponseNative(
            status_code=_UniffiFfiConverterUInt16.read(buf),
            content_type=_UniffiFfiConverterOptionalString.read(buf),
            body=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt16.check_lower(value.status_code)
        _UniffiFfiConverterOptionalString.check_lower(value.content_type)
        _UniffiFfiConverterString.check_lower(value.body)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt16.write(value.status_code, buf)
        _UniffiFfiConverterOptionalString.write(value.content_type, buf)
        _UniffiFfiConverterString.write(value.body, buf)



# FfiError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class FfiError(Exception):
    pass

_UniffiTempFfiError = FfiError

class FfiError:  # type: ignore

    class BuildFailed(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.BuildFailed({})".format(repr(str(self)))
    _UniffiTempFfiError.BuildFailed = BuildFailed # type: ignore
    class JoinFailed(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.JoinFailed({})".format(repr(str(self)))
    _UniffiTempFfiError.JoinFailed = JoinFailed # type: ignore
    class DiscoveryFailed(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.DiscoveryFailed({})".format(repr(str(self)))
    _UniffiTempFfiError.DiscoveryFailed = DiscoveryFailed # type: ignore
    class StreamFailed(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.StreamFailed({})".format(repr(str(self)))
    _UniffiTempFfiError.StreamFailed = StreamFailed # type: ignore
    class HostUnavailable(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.HostUnavailable({})".format(repr(str(self)))
    _UniffiTempFfiError.HostUnavailable = HostUnavailable # type: ignore
    class ServingUnsupported(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.ServingUnsupported({})".format(repr(str(self)))
    _UniffiTempFfiError.ServingUnsupported = ServingUnsupported # type: ignore
    class NativeRuntimeFailed(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.NativeRuntimeFailed({})".format(repr(str(self)))
    _UniffiTempFfiError.NativeRuntimeFailed = NativeRuntimeFailed # type: ignore
    class OpenAiRequestFailed(_UniffiTempFfiError):
        def __repr__(self):
            return "FfiError.OpenAiRequestFailed({})".format(repr(str(self)))
    _UniffiTempFfiError.OpenAiRequestFailed = OpenAiRequestFailed # type: ignore

FfiError = _UniffiTempFfiError # type: ignore
del _UniffiTempFfiError


class _UniffiFfiConverterTypeFfiError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiError.BuildFailed(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return FfiError.JoinFailed(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return FfiError.DiscoveryFailed(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return FfiError.StreamFailed(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return FfiError.HostUnavailable(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 6:
            return FfiError.ServingUnsupported(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 7:
            return FfiError.NativeRuntimeFailed(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 8:
            return FfiError.OpenAiRequestFailed(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, FfiError.BuildFailed):
            return
        if isinstance(value, FfiError.JoinFailed):
            return
        if isinstance(value, FfiError.DiscoveryFailed):
            return
        if isinstance(value, FfiError.StreamFailed):
            return
        if isinstance(value, FfiError.HostUnavailable):
            return
        if isinstance(value, FfiError.ServingUnsupported):
            return
        if isinstance(value, FfiError.NativeRuntimeFailed):
            return
        if isinstance(value, FfiError.OpenAiRequestFailed):
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, FfiError.BuildFailed):
            buf.write_i32(1)
        if isinstance(value, FfiError.JoinFailed):
            buf.write_i32(2)
        if isinstance(value, FfiError.DiscoveryFailed):
            buf.write_i32(3)
        if isinstance(value, FfiError.StreamFailed):
            buf.write_i32(4)
        if isinstance(value, FfiError.HostUnavailable):
            buf.write_i32(5)
        if isinstance(value, FfiError.ServingUnsupported):
            buf.write_i32(6)
        if isinstance(value, FfiError.NativeRuntimeFailed):
            buf.write_i32(7)
        if isinstance(value, FfiError.OpenAiRequestFailed):
            buf.write_i32(8)






class NativeRuntimePruneModeNative(enum.Enum):

    KEEP_ACTIVE_AND_PREVIOUS = 0

    ACTIVE_ONLY = 1



class _UniffiFfiConverterTypeNativeRuntimePruneModeNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return NativeRuntimePruneModeNative.KEEP_ACTIVE_AND_PREVIOUS
        if variant == 2:
            return NativeRuntimePruneModeNative.ACTIVE_ONLY
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == NativeRuntimePruneModeNative.KEEP_ACTIVE_AND_PREVIOUS:
            return
        if value == NativeRuntimePruneModeNative.ACTIVE_ONLY:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == NativeRuntimePruneModeNative.KEEP_ACTIVE_AND_PREVIOUS:
            buf.write_i32(1)
        if value == NativeRuntimePruneModeNative.ACTIVE_ONLY:
            buf.write_i32(2)



class _UniffiFfiConverterOptionalUInt16(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt16.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt16.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt16.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")






class OpenAiStreamEventNative:
    def __init__(self):
        raise RuntimeError("OpenAiStreamEventNative cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class STARTED:

        def __init__(self, request_id:str, status_code:int, content_type:typing.Optional[str]):
            self.request_id = request_id


            self.status_code = status_code


            self.content_type = content_type


            pass





        def __str__(self):
            return "OpenAiStreamEventNative.STARTED(request_id={}, status_code={}, content_type={})".format(self.request_id, self.status_code, self.content_type)
        def __eq__(self, other):
            if not isinstance(other, OpenAiStreamEventNative):
                return NotImplemented
            if not other.is_STARTED():
                return False
            if self.request_id != other.request_id:
                return False
            if self.status_code != other.status_code:
                return False
            if self.content_type != other.content_type:
                return False
            return True

    @dataclass
    class SSE:

        def __init__(self, request_id:str, event_type:typing.Optional[str], data:str, raw:str):
            self.request_id = request_id


            self.event_type = event_type


            self.data = data


            self.raw = raw


            pass





        def __str__(self):
            return "OpenAiStreamEventNative.SSE(request_id={}, event_type={}, data={}, raw={})".format(self.request_id, self.event_type, self.data, self.raw)
        def __eq__(self, other):
            if not isinstance(other, OpenAiStreamEventNative):
                return NotImplemented
            if not other.is_SSE():
                return False
            if self.request_id != other.request_id:
                return False
            if self.event_type != other.event_type:
                return False
            if self.data != other.data:
                return False
            if self.raw != other.raw:
                return False
            return True

    @dataclass
    class COMPLETED:

        def __init__(self, request_id:str):
            self.request_id = request_id


            pass





        def __str__(self):
            return "OpenAiStreamEventNative.COMPLETED(request_id={})".format(self.request_id)
        def __eq__(self, other):
            if not isinstance(other, OpenAiStreamEventNative):
                return NotImplemented
            if not other.is_COMPLETED():
                return False
            if self.request_id != other.request_id:
                return False
            return True

    @dataclass
    class FAILED:

        def __init__(self, request_id:str, status_code:typing.Optional[int], error:str, body:typing.Optional[str]):
            self.request_id = request_id


            self.status_code = status_code


            self.error = error


            self.body = body


            pass





        def __str__(self):
            return "OpenAiStreamEventNative.FAILED(request_id={}, status_code={}, error={}, body={})".format(self.request_id, self.status_code, self.error, self.body)
        def __eq__(self, other):
            if not isinstance(other, OpenAiStreamEventNative):
                return NotImplemented
            if not other.is_FAILED():
                return False
            if self.request_id != other.request_id:
                return False
            if self.status_code != other.status_code:
                return False
            if self.error != other.error:
                return False
            if self.body != other.body:
                return False
            return True



    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_STARTED(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.STARTED)
    def is_started(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.STARTED)
    def is_SSE(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.SSE)
    def is_sse(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.SSE)
    def is_COMPLETED(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.COMPLETED)
    def is_completed(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.COMPLETED)
    def is_FAILED(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.FAILED)
    def is_failed(self) -> bool:
        return isinstance(self, OpenAiStreamEventNative.FAILED)


# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
OpenAiStreamEventNative.STARTED = type("OpenAiStreamEventNative.STARTED", (OpenAiStreamEventNative.STARTED, OpenAiStreamEventNative,), {})  # type: ignore
OpenAiStreamEventNative.SSE = type("OpenAiStreamEventNative.SSE", (OpenAiStreamEventNative.SSE, OpenAiStreamEventNative,), {})  # type: ignore
OpenAiStreamEventNative.COMPLETED = type("OpenAiStreamEventNative.COMPLETED", (OpenAiStreamEventNative.COMPLETED, OpenAiStreamEventNative,), {})  # type: ignore
OpenAiStreamEventNative.FAILED = type("OpenAiStreamEventNative.FAILED", (OpenAiStreamEventNative.FAILED, OpenAiStreamEventNative,), {})  # type: ignore




class _UniffiFfiConverterTypeOpenAiStreamEventNative(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return OpenAiStreamEventNative.STARTED(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterUInt16.read(buf),
                _UniffiFfiConverterOptionalString.read(buf),
            )
        if variant == 2:
            return OpenAiStreamEventNative.SSE(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterOptionalString.read(buf),
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return OpenAiStreamEventNative.COMPLETED(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return OpenAiStreamEventNative.FAILED(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterOptionalUInt16.read(buf),
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterOptionalString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_STARTED():
            _UniffiFfiConverterString.check_lower(value.request_id)
            _UniffiFfiConverterUInt16.check_lower(value.status_code)
            _UniffiFfiConverterOptionalString.check_lower(value.content_type)
            return
        if value.is_SSE():
            _UniffiFfiConverterString.check_lower(value.request_id)
            _UniffiFfiConverterOptionalString.check_lower(value.event_type)
            _UniffiFfiConverterString.check_lower(value.data)
            _UniffiFfiConverterString.check_lower(value.raw)
            return
        if value.is_COMPLETED():
            _UniffiFfiConverterString.check_lower(value.request_id)
            return
        if value.is_FAILED():
            _UniffiFfiConverterString.check_lower(value.request_id)
            _UniffiFfiConverterOptionalUInt16.check_lower(value.status_code)
            _UniffiFfiConverterString.check_lower(value.error)
            _UniffiFfiConverterOptionalString.check_lower(value.body)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_STARTED():
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value.request_id, buf)
            _UniffiFfiConverterUInt16.write(value.status_code, buf)
            _UniffiFfiConverterOptionalString.write(value.content_type, buf)
        if value.is_SSE():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.request_id, buf)
            _UniffiFfiConverterOptionalString.write(value.event_type, buf)
            _UniffiFfiConverterString.write(value.data, buf)
            _UniffiFfiConverterString.write(value.raw, buf)
        if value.is_COMPLETED():
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value.request_id, buf)
        if value.is_FAILED():
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value.request_id, buf)
            _UniffiFfiConverterOptionalUInt16.write(value.status_code, buf)
            _UniffiFfiConverterString.write(value.error, buf)
            _UniffiFfiConverterOptionalString.write(value.body, buf)



class _UniffiFfiConverterSequenceTypeModelNative(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeModelNative.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeModelNative.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeModelNative.read(buf) for i in range(count)
        ]




class OpenAiStreamListener(typing.Protocol):

    def on_event(self, event: OpenAiStreamEventNative) -> None:
        raise NotImplementedError
# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplOpenAiStreamListenerImpl:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_MESH_FFI_OPEN_AI_STREAM_LISTENER_METHOD0
    def on_event(
            uniffi_handle,
            event,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiFfiConverterTypeOpenAiStreamListener._handle_map.get(uniffi_handle)
        def make_call():
            uniffi_args = (_UniffiFfiConverterTypeOpenAiStreamEventNative.lift(event), )
            uniffi_method = uniffi_obj.on_event
            return uniffi_method(*uniffi_args)
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE_MESH_FFI_OPEN_AI_STREAM_LISTENER
    def _uniffi_free(uniffi_handle):
        _UniffiFfiConverterTypeOpenAiStreamListener._handle_map.remove(uniffi_handle)

    @_UNIFFI_CALLBACK_INTERFACE_CLONE_MESH_FFI_OPEN_AI_STREAM_LISTENER
    def _uniffi_clone(uniffi_handle):
        return _UniffiFfiConverterTypeOpenAiStreamListener._handle_map.clone(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceMeshFfiOpenAiStreamListener(
        _uniffi_free,
        _uniffi_clone,
        on_event,
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_meshllm_ffi_fn_init_callback_vtable_openaistreamlistener(ctypes.byref(_uniffi_vtable))

# The _UniffiConverter which transforms the Callbacks in to Handles to pass to Rust.
_UniffiFfiConverterTypeOpenAiStreamListener = _UniffiCallbackInterfaceFfiConverter()


class MeshNodeHandleProtocol(typing.Protocol):

    def cancel(self, request_id: str) -> None:
        raise NotImplementedError
    def inference_list_models(self, ) -> typing.List[ModelNative]:
        raise NotImplementedError
    def join_token(self, token: str) -> None:
        raise NotImplementedError
    def openai_request(self, path: str,body_json: str) -> OpenAiResponseNative:
        raise NotImplementedError
    def openai_stream(self, path: str,body_json: str,listener: OpenAiStreamListener) -> str:
        raise NotImplementedError
    def start(self, ) -> None:
        raise NotImplementedError
    def status(self, ) -> NodeStatusNative:
        raise NotImplementedError
    def stop(self, ) -> None:
        raise NotImplementedError

class MeshNodeHandle(MeshNodeHandleProtocol):

    _handle: ctypes.c_uint64

    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_meshllm_ffi_fn_free_meshnodehandle, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_meshllm_ffi_fn_clone_meshnodehandle, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def cancel(self, request_id: str) -> None:

        _UniffiFfiConverterString.check_lower(request_id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(request_id),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_cancel,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def inference_list_models(self, ) -> typing.List[ModelNative]:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceTypeModelNative.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_inference_list_models,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def join_token(self, token: str) -> None:

        _UniffiFfiConverterString.check_lower(token)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(token),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_join_token,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def openai_request(self, path: str,body_json: str) -> OpenAiResponseNative:

        _UniffiFfiConverterString.check_lower(path)

        _UniffiFfiConverterString.check_lower(body_json)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(path),
            _UniffiFfiConverterString.lower(body_json),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeOpenAiResponseNative.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_openai_request,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def openai_stream(self, path: str,body_json: str,listener: OpenAiStreamListener) -> str:

        _UniffiFfiConverterString.check_lower(path)

        _UniffiFfiConverterString.check_lower(body_json)

        _UniffiFfiConverterTypeOpenAiStreamListener.check_lower(listener)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(path),
            _UniffiFfiConverterString.lower(body_json),
            _UniffiFfiConverterTypeOpenAiStreamListener.lower(listener),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_openai_stream,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def start(self, ) -> None:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_start,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def status(self, ) -> NodeStatusNative:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeNodeStatusNative.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_status,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def stop(self, ) -> None:
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_meshllm_ffi_fn_method_meshnodehandle_stop,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeMeshNodeHandle:
    @staticmethod
    def lift(value: int) -> MeshNodeHandle:
        return MeshNodeHandle._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: MeshNodeHandle):
        if not isinstance(value, MeshNodeHandle):
            raise TypeError("Expected MeshNodeHandle instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: MeshNodeHandle) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> MeshNodeHandle:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: MeshNodeHandle, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))




class NativeRuntimeProgressListener(typing.Protocol):

    def on_progress(self, event: NativeRuntimeDownloadProgressNative) -> None:
        raise NotImplementedError
# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplNativeRuntimeProgressListenerImpl:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER_METHOD0
    def on_progress(
            uniffi_handle,
            event,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiFfiConverterTypeNativeRuntimeProgressListener._handle_map.get(uniffi_handle)
        def make_call():
            uniffi_args = (_UniffiFfiConverterTypeNativeRuntimeDownloadProgressNative.lift(event), )
            uniffi_method = uniffi_obj.on_progress
            return uniffi_method(*uniffi_args)
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER
    def _uniffi_free(uniffi_handle):
        _UniffiFfiConverterTypeNativeRuntimeProgressListener._handle_map.remove(uniffi_handle)

    @_UNIFFI_CALLBACK_INTERFACE_CLONE_MESH_FFI_NATIVE_RUNTIME_PROGRESS_LISTENER
    def _uniffi_clone(uniffi_handle):
        return _UniffiFfiConverterTypeNativeRuntimeProgressListener._handle_map.clone(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceMeshFfiNativeRuntimeProgressListener(
        _uniffi_free,
        _uniffi_clone,
        on_progress,
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_meshllm_ffi_fn_init_callback_vtable_nativeruntimeprogresslistener(ctypes.byref(_uniffi_vtable))

# The _UniffiConverter which transforms the Callbacks in to Handles to pass to Rust.
_UniffiFfiConverterTypeNativeRuntimeProgressListener = _UniffiCallbackInterfaceFfiConverter()

class _UniffiFfiConverterOptionalTypeNativeRuntimeProgressListener(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeNativeRuntimeProgressListener.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeNativeRuntimeProgressListener.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeNativeRuntimeProgressListener.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterSequenceTypeInstalledNativeRuntimeNative(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeInstalledNativeRuntimeNative.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeInstalledNativeRuntimeNative.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeInstalledNativeRuntimeNative.read(buf) for i in range(count)
        ]
def create_node(mode: str,join_tokens: typing.List[str],models: typing.List[str],auto_join: bool,owner_key_path: typing.Optional[str],api_port: int,console_port: int) -> MeshNodeHandle:

    _UniffiFfiConverterString.check_lower(mode)

    _UniffiFfiConverterSequenceString.check_lower(join_tokens)

    _UniffiFfiConverterSequenceString.check_lower(models)

    _UniffiFfiConverterBoolean.check_lower(auto_join)

    _UniffiFfiConverterOptionalString.check_lower(owner_key_path)

    _UniffiFfiConverterUInt16.check_lower(api_port)

    _UniffiFfiConverterUInt16.check_lower(console_port)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(mode),
        _UniffiFfiConverterSequenceString.lower(join_tokens),
        _UniffiFfiConverterSequenceString.lower(models),
        _UniffiFfiConverterBoolean.lower(auto_join),
        _UniffiFfiConverterOptionalString.lower(owner_key_path),
        _UniffiFfiConverterUInt16.lower(api_port),
        _UniffiFfiConverterUInt16.lower(console_port),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeMeshNodeHandle.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_create_node,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def current_mesh_version() -> str:
    _uniffi_lowered_args = (
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_current_mesh_version,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def current_skippy_abi_version() -> str:
    _uniffi_lowered_args = (
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_current_skippy_abi_version,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def install_native_runtime(options: NativeRuntimeInstallOptionsNative,progress: typing.Optional[NativeRuntimeProgressListener]) -> NativeRuntimeInstallOutcomeNative:

    _UniffiFfiConverterTypeNativeRuntimeInstallOptionsNative.check_lower(options)

    _UniffiFfiConverterOptionalTypeNativeRuntimeProgressListener.check_lower(progress)
    _uniffi_lowered_args = (
        _UniffiFfiConverterTypeNativeRuntimeInstallOptionsNative.lower(options),
        _UniffiFfiConverterOptionalTypeNativeRuntimeProgressListener.lower(progress),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeNativeRuntimeInstallOutcomeNative.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_install_native_runtime,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def installed_native_runtimes(cache_dir: typing.Optional[str]) -> typing.List[InstalledNativeRuntimeNative]:

    _UniffiFfiConverterOptionalString.check_lower(cache_dir)
    _uniffi_lowered_args = (
        _UniffiFfiConverterOptionalString.lower(cache_dir),
    )
    _uniffi_lift_return = _UniffiFfiConverterSequenceTypeInstalledNativeRuntimeNative.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_installed_native_runtimes,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def prune_native_runtimes(cache_dir: typing.Optional[str],active_mesh_version: typing.Optional[str],mode: NativeRuntimePruneModeNative) -> NativeRuntimePruneResultNative:

    _UniffiFfiConverterOptionalString.check_lower(cache_dir)

    _UniffiFfiConverterOptionalString.check_lower(active_mesh_version)

    _UniffiFfiConverterTypeNativeRuntimePruneModeNative.check_lower(mode)
    _uniffi_lowered_args = (
        _UniffiFfiConverterOptionalString.lower(cache_dir),
        _UniffiFfiConverterOptionalString.lower(active_mesh_version),
        _UniffiFfiConverterTypeNativeRuntimePruneModeNative.lower(mode),
    )
    _uniffi_lift_return = _UniffiFfiConverterTypeNativeRuntimePruneResultNative.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_prune_native_runtimes,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def remove_native_runtime(cache_dir: typing.Optional[str],mesh_version: str,native_runtime_id: str) -> bool:

    _UniffiFfiConverterOptionalString.check_lower(cache_dir)

    _UniffiFfiConverterString.check_lower(mesh_version)

    _UniffiFfiConverterString.check_lower(native_runtime_id)
    _uniffi_lowered_args = (
        _UniffiFfiConverterOptionalString.lower(cache_dir),
        _UniffiFfiConverterString.lower(mesh_version),
        _UniffiFfiConverterString.lower(native_runtime_id),
    )
    _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeFfiError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_meshllm_ffi_fn_func_remove_native_runtime,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "NativeRuntimeVerificationPolicyNative",
    "FfiError",
    "NativeRuntimePruneModeNative",
    "OpenAiStreamEventNative",
    "InstalledNativeRuntimeNative",
    "ModelNative",
    "NativeRuntimeDownloadProgressNative",
    "NativeRuntimeInstallOptionsNative",
    "NativeRuntimeInstallOutcomeNative",
    "NativeRuntimePruneResultNative",
    "NodeStatusNative",
    "OpenAiResponseNative",
    "create_node",
    "current_mesh_version",
    "current_skippy_abi_version",
    "install_native_runtime",
    "installed_native_runtimes",
    "prune_native_runtimes",
    "remove_native_runtime",
    "MeshNodeHandle",
    "MeshNodeHandleProtocol",
    "OpenAiStreamListener",
    "NativeRuntimeProgressListener",
]